name: Test setup-php action
on: [push]
jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: ['macOS-latest', 'ubuntu-latest']
                version: ['7.1', '7.2', '7.3']
        steps:
            - uses: actions/checkout@v1
            -
                name: Setup
                uses: ./
                with:
                    version: ${{ matrix.version }}
            -
                name: Display PHP version
                run: 'php -r "if (PHP_MAJOR_VERSION.\'.\'.PHP_MINOR_VERSION !== \'${{ matrix.version }}\') exit 1;"'
            -
                name: Display Composer version
                run: 'composer --version'
